frase = 'curso em video Python'
print(frase)
print(frase[3])
print(frase[3:13])
print(frase[:13])
print(frase[10:])
print(frase[1:15:2])
print(frase.count('o'))
print(len(frase))
print(frase.replace('Python', 'Android'))
print(frase.find('video'))
print(frase.split())
