t = int(input('Digite um numero para ver sua tabuada: '))

print('=' * 15)
print('{} x {} = {}'.format(t, 1, t*1))
print('{} x {} = {}'.format(t, 2, t*2))
print('{} x {} = {}'.format(t, 3, t*3))
print(t, 'x', '4', '=', t*4)
print(t, 'x', '5', '=', t*5)
print(t, 'x', '6', '=', t*6)
print(t, 'x', '7', '=', t*7)
print(t, 'x', '8', '=', t*8)
print(t, 'x', '9', '=', t*9)
print(t, 'x', '10', '=', t*10)
print('=' * 15)
