nome = str(input('Digite seu nome: ')).strip()
separa = nome.split()

print()
print('Analisando  seu nome....')
print()
print('Seu nome em Maiusculo é {}'.format(nome.upper()))
print('Seu nome em Minusculo é {}'.format(nome.lower()))
print('Seu nome tem ao todo {} letras'.format(len(nome)-nome.count(' ')))
print('Seu primeiro nome é {} e ele tem {} letras'.format(separa[0], len(separa[0])))